package pl.com.bottega.rekrutacja;

/**
 * Created by macie on 12.12.2016.
 *  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 *   Każdy nowy termin w ciągu Fibonacciego jest generowany przez dodanie dwóch poprzednich wartości. Zaczynając od 1 i 2, pierwsze 10 będą:
 *   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *    Dzięki uwzględnieniu warunków w ciągu Fibonacciego, których wartość nie przekracza cztery miliony znaleźć sumę.
 */
public class FibbonaciNumbers {

    public static void main(String[] args) {
        int first = 1;
        int second = 2;
        int number = 0;

        System.out.print(first + ", " + second);

        while (first + second < 4000000) {
            number = first + second;
            first = second;
            second = number;

            System.out.print(", " + number);
        }
    }

}
